### ISSUE TITLE
[4.14] Android system warning message: Internal problem with your device

### ISSUE THREAD

**Issue by anht3889** [kerneltoast/simple_lmk#4]
Dear sir,

I just included simple_lmk into my kernel: https://github.com/anht3889/LGE_G820_Kernel_Caf/tree/simple_lmk
The kernel is working really well but I encounter the message Internal hardware problem every tiime I turn on or restart the phone.
Is this normal and do we have any solution to fix that. 

Thank you so much for your great work.

**Comment by anht3889** [comment]
@kerneltoast Would you please take a look at this. Thank you so much.

**Comment by msfjarvis** [comment]
It's not a Simple LMK problem, but a result of any change to your kernel's defconfig. Looking around for the kernel patch that fools Android into thinking that the defconfig was not changed is left as an exercise for the reader.

**Comment by YumeMichi** [comment]
https://github.com/kerneltoast/android_kernel_google_wahoo/commit/c7d40bf203ae3887b0a18b5c51b6006dc0cc7a1d

**Comment by anht3889** [comment]
@YumeMichi @msfjarvis You made my date. I can resolve the issue now. Thank you!
